version: "3.8"
services:
  postgres:
    image: postgres:10.3
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password123
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  prisma:
    image: events
    restart: always
    depends_on:
      - "postgres"
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=postgresql://postgres:password123@postgres:5432/mydb?schema=public
  react:
    image: event_app_frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://prisma:4000
volumes:
  postgres:
